Repository project-koku/masu, pull requests merged in 2018-09, with the labels that each got.

#175 Fixed bad default value for keyword arg.
  masu/processor/tasks.py
Labels: bug

#178 raise error for download task failure.
  masu/processor/_tasks/download.py
  tests/processor/test_tasks.py
Labels: enhancement

#182 Add ReportProcessor interface to support multiple processors
  masu/processor/_tasks/process.py
  masu/processor/providers/__init__.py
  masu/processor/providers/aws_report_processor.py
  masu/processor/report_processor.py
  masu/processor/tasks.py
  tests/processor/providers/__init__.py
  tests/processor/providers/test_aws_report_processor.py
  tests/processor/test_report_processor.py
  tests/processor/test_tasks.py
Labels: enhancement

#184 Store AWS account aliases if available.
  masu/database/account_alias_accessor.py
  masu/external/account_label.py
  masu/external/accounts/labels/__init__.py
  masu/external/accounts/labels/aws/__init__.py
  masu/external/accounts/labels/aws/aws_account_alias.py
  masu/external/downloader/aws/aws_report_downloader.py
  masu/external/downloader/local/local_report_downloader.py
  masu/processor/orchestrator.py
  masu/util/aws/common.py
  tests/external/accounts/labels/__init__.py
  tests/external/accounts/labels/aws/__init__.py
  tests/external/accounts/labels/aws/test_aws_account_alias.py
  tests/external/downloader/aws/test_aws_report_downloader.py
  tests/external/test_account_label.py
  tests/processor/test_orchestrator.py
  tests/sql/test.sql
  tests/util/aws/test_common.py
Labels: enhancement

#188 Adding timeout exception for celery status
  masu/api/status.py
Labels: bug

#194 using moto 1.3.4
  Pipfile
  Pipfile.lock
Labels: configuration

#192 Catching exception for missing manifest
  masu/external/downloader/aws/aws_report_downloader.py
  tests/external/downloader/aws/test_aws_report_downloader.py
Labels: enhancement

#205 Renaming Local provider to AWS-local
  masu/external/__init__.py
  masu/external/downloader/aws_local/__init__.py
  masu/external/downloader/aws_local/aws_local_report_downloader.py
  masu/external/report_downloader.py
  masu/processor/report_processor.py
  tests/external/downloader/aws_local/__init__.py
  tests/external/downloader/aws_local/test_aws_local_report_downloader.py
  tests/processor/test_report_processor.py
Labels: enhancement

#204 Load earlier months of data when adding new providers.
  masu/config.py
  masu/database/provider_db_accessor.py
  masu/external/accounts/db/cur_accounts_db.py
  masu/external/downloader/aws/aws_report_downloader.py
  masu/external/downloader/aws_local/aws_local_report_downloader.py
  masu/external/downloader/downloader_interface.py
  masu/external/report_downloader.py
  masu/processor/_tasks/download.py
  masu/processor/_tasks/process.py
  masu/processor/tasks.py
  tests/database/test_provider_db_accessor.py
  tests/external/accounts/db/test_cur_accounts_db.py
  tests/external/downloader/aws/test_aws_report_downloader.py
  tests/external/downloader/aws_local/test_aws_local_report_downloader.py
  tests/external/test_report_downloader.py
  tests/processor/test_orchestrator.py
  tests/processor/test_tasks.py
  tests/sql/test.sql
Labels: enhancement

#207 initializing alias to account id.
  masu/database/account_alias_accessor.py
  tests/database/test_account_alias_accessor.py
Labels: enhancement

#209 Test database schema update and database change for OCP
  masu/database/provider_billing_source_db_accessor.py
  tests/sql/test.sql
Labels: enhancement

#206 Adding usage_end to summary tables.
  masu/database/sql/reporting_awscostentrylineitem_daily.sql
  masu/database/sql/reporting_awscostentrylineitem_daily_summary.sql
  tests/database/test_report_db_accessor.py
  tests/processor/test_tasks.py
  tests/sql/test.sql
Labels: enhancement

#211 OCP local ingesting and processing stubs
  masu/api/report_data.py
  masu/config.py
  masu/external/__init__.py
  masu/external/downloader/ocp_local/__init__.py
  masu/external/downloader/ocp_local/ocp_local_report_downloader.py
  masu/external/report_downloader.py
  masu/processor/_tasks/process.py
  masu/processor/aws/aws_report_processor.py
  masu/processor/ocp/__init__.py
  masu/processor/ocp/ocp_report_processor.py
  masu/processor/report_processor.py
  masu/processor/report_processor_base.py
  masu/processor/tasks.py
  masu/util/ocp/__init__.py
  masu/util/ocp/common.py
  tests/api/test_report_data.py
  tests/data/pod-cpu-usage-ocp.csv
  tests/external/downloader/ocp_local/__init__.py
  tests/external/downloader/ocp_local/test_ocp_local_report_downloader.py
  tests/external/test_report_downloader.py
  tests/processor/aws/test_aws_report_processor.py
  tests/processor/ocp/__init__.py
  tests/processor/ocp/test_ocp_report_processor.py
  tests/processor/test_report_processor.py
  tests/processor/test_tasks.py
Labels: enhancement

#215 3scale gateway integration changes
  masu/config.py
  masu/database/auth_db_accessor.py
  masu/database/customer_db_accessor.py
  masu/database/provider_db_accessor.py
  tests/api/test_expired_data.py
  tests/api/test_report_data.py
  tests/create_db.sh
  tests/database/test_account_alias_accessor.py
  tests/database/test_auth_db_accessor.py
  tests/database/test_customer_db_accessor.py
  tests/database/test_provider_db_accessor.py
  tests/database/test_report_db_accessor.py
  tests/database/test_report_db_cleaner.py
  tests/external/accounts/db/test_cur_accounts_db.py
  tests/external/accounts/labels/aws/test_aws_account_alias.py
  tests/external/accounts/network/test_cur_accounts_network.py
  tests/external/test_account_label.py
  tests/external/test_accounts_accessor.py
  tests/processor/aws/test_aws_report_db_cleaner.py
  tests/processor/aws/test_aws_report_processor.py
  tests/processor/ocp/test_ocp_report_processor.py
  tests/processor/test_expired_data_remover.py
  tests/processor/test_orchestrator.py
  tests/processor/test_report_processor.py
  tests/processor/test_tasks.py
  tests/sql/test.sql
Labels: enhancement

#218 Creating a report db accessor base class
  masu/database/report_db_accessor.py
  masu/database/report_db_accessor_base.py
  tests/database/test_report_db_accessor.py
Labels: enhancement
