Repository project-koku/masu, pull requests merged in 2019-01, with the labels that each got.

#310 updating compose db credentials
  docker-compose.yml
Labels: configuration

#314 Fixing date related test cases and pip env
  Pipfile.lock
  tests/processor/aws/test_aws_report_db_cleaner.py
  tests/processor/aws/test_aws_report_summary_updater.py
  tests/processor/ocp/test_ocp_report_summary_updater.py
  tests/processor/test_tasks.py
Labels: bug

#317 Database accessor context manager
  Dockerfile
  Dockerfile-test
  masu/api/report_data.py
  masu/api/status.py
  masu/config.py
  masu/database/koku_database_access.py
  masu/database/provider_db_accessor.py
  masu/database/report_db_accessor_base.py
  masu/external/accounts/db/cur_accounts_db.py
  masu/external/accounts/labels/aws/aws_account_alias.py
  masu/external/downloader/report_downloader_base.py
  masu/external/report_downloader.py
  masu/processor/_tasks/download.py
  masu/processor/_tasks/process.py
  masu/processor/aws/aws_report_db_cleaner.py
  masu/processor/aws/aws_report_processor.py
  masu/processor/aws/aws_report_summary_updater.py
  masu/processor/ocp/ocp_report_charge_updater.py
  masu/processor/ocp/ocp_report_db_cleaner.py
  masu/processor/ocp/ocp_report_processor.py
  masu/processor/ocp/ocp_report_summary_updater.py
  masu/processor/report_charge_updater.py
  masu/processor/tasks.py
  masu/util/aws/region_map.py
  tests/external/downloader/aws/test_aws_report_downloader.py
  tests/processor/aws/test_aws_report_processor.py
  tests/processor/aws/test_aws_report_summary_updater.py
  tests/processor/ocp/test_ocp_report_charge_updater.py
  tests/processor/ocp/test_ocp_report_processor.py
  tests/processor/ocp/test_ocp_report_summary_updater.py
  tests/processor/test_tasks.py
  tests/util/aws/test_region_map.py
Labels: bug

#319 Except a socket timeout when checking celery status
  masu/api/status.py
Labels: bug

#321 moving download endpoint to enqueue async task
  masu/api/download.py
  tests/api/test_download.py
Labels: enhancement

#324 Default to running summary SQL for 3 day period to catch boundary data
  masu/processor/aws/aws_report_summary_updater.py
  masu/processor/ocp/ocp_report_summary_updater.py
  masu/processor/tasks.py
  tests/processor/test_tasks.py
Labels: bug

#327 Preliminary AWS tag updates
  docker-compose.yml
  masu/processor/aws/aws_report_processor.py
  tests/processor/aws/test_aws_report_processor.py
  tests/sql/test.sql
Labels: enhancement

#330 Use non-changing columns for hash calculation to dedup
  masu/processor/aws/aws_report_processor.py
  tests/processor/aws/test_aws_report_processor.py
Labels: bug

#344 Add a podlabel_summary processing to populate table with OCP tags
  masu/database/__init__.py
  masu/database/ocp_report_db_accessor.py
  masu/database/sql/reporting_ocpusagepodlabel_summary.sql
  masu/processor/ocp/ocp_report_summary_updater.py
  tests/database/test_ocp_report_db_accessor.py
  tests/sql/test.sql
Labels: enhancement, tech-debt-high

#351 Updates to support AWS tag report filter/group_by
  masu/database/__init__.py
  masu/database/aws_report_db_accessor.py
  masu/database/sql/reporting_awscostentrylineitem_aggregates.sql
  masu/database/sql/reporting_awscostentrylineitem_daily_summary.sql
  masu/database/sql/reporting_awstags_summary.sql
  masu/processor/aws/aws_report_summary_updater.py
  tests/database/test_aws_report_db_accessor.py
  tests/database/test_reporting_common_db_accessor.py
  tests/processor/aws/test_aws_report_processor.py
  tests/sql/test.sql
Labels: enhancement

#353 Prevent masu-scheduler from attempting to connect to Kafka server
  Makefile
  masu/config.py
  masu/external/kafka_msg_handler.py
  openshift/configmap.yaml
  openshift/masu.yaml
  openshift/scheduler.yaml
  openshift/worker.yaml
Labels: configuration
