Repository project-koku/masu, pull requests merged in 2019-05, with the labels that each got.

#431 Bugfix opc aws by project
  masu/database/sql/reporting_ocpawscostlineitem_daily_summary.sql
Labels: bug

#433 Provider remove summary data
  masu/database/aws_report_db_accessor.py
  masu/database/ocp_report_db_accessor.py
  masu/processor/aws/aws_report_db_cleaner.py
  masu/processor/ocp/ocp_report_db_cleaner.py
Labels: enhancement

#442 Fixing OCP-on-AWS summary table removal
  masu/database/ocp_report_db_accessor.py
  masu/processor/aws/aws_report_db_cleaner.py
  masu/processor/ocp/ocp_report_charge_updater.py
  masu/processor/ocp/ocp_report_db_cleaner.py
  tests/sql/test.sql
Labels: bug

#443 implement ProviderStatus, fixes #405
  Pipfile
  Pipfile.lock
  masu/database/provider_status_accessor.py
  masu/processor/_tasks/download.py
  masu/processor/orchestrator.py
  masu/providers/status.py
  tests/database/test_provider_status_accessor.py
  tests/processor/test_orchestrator.py
  tests/processor/test_tasks.py
  tests/providers/test_status.py
  tests/sql/test.sql
Labels: enhancement

#451 Changing kafka msg validation from hash to request_id
  masu/external/kafka_msg_handler.py
Labels: configuration

#452 Breakout summary celery task from processing chain
  docker-compose.yml
  masu/celery/__init__.py
  masu/processor/orchestrator.py
  masu/processor/tasks.py
  tests/processor/test_orchestrator.py
  tests/processor/test_tasks.py
Labels: enhancement
